import "server-only";
import codesJson from "@/app/content/seo/codes.json";
import problemsJson from "@/app/content/seo/problems.json";
import type { Diagnosis } from "@/app/types/chat";

// Data for the public /codes and /problems pages. It's generated by
// `rake marketing:seo_dataset` in mechanicai-backend (same diagnosis format as
// the app) and copied here, so pages make no AI calls. Each entry has a
// publish_on date (`rake marketing:seo_schedule`) and exists on the site from
// that day: the pages revalidate daily, so weekly batches go live without a
// deploy.

type Report = Omit<Diagnosis, "summary" | "vehicle">;

type Entry = Report & {
  title: string;
  system: string;
  answer: string;
  meaning: string;
  symptoms: string[];
  faqs: { question: string; answer: string }[];
  related_codes: string[];
  related_problems: string[];
  generated_at: string;
  publish_on: string;
};

export type CodeEntry = Entry & { code: string };
export type ProblemEntry = Entry & { slug: string; query: string };

const allCodes = codesJson as CodeEntry[];
const allProblems = problemsJson as ProblemEntry[];
const codesById = new Map(allCodes.map((c) => [c.code, c]));
const problemsBySlug = new Map(allProblems.map((p) => [p.slug, p]));

// Checked on every render, not at import: a long-running server must pick up
// each day's batch. Dates are UTC days.
const isLive = (entry: Entry) => entry.publish_on <= new Date().toISOString().slice(0, 10);
const live = <T extends Entry>(entry: T | undefined) => (entry && isLive(entry) ? entry : undefined);

// The codes that fail US emissions tests most often (Illinois EPA data), shown
// first on /codes.
const POPULAR = [
  "P0420", "P0171", "P0300", "P0401", "P0174", "P0442", "P0455", "P0440",
  "P0141", "P0430", "P0135", "P0446", "P0128", "P0301", "P0411", "P0133",
];

export const getCodes = () => allCodes.filter(isLive);
export const getProblems = () => allProblems.filter(isLive);
export const getCode = (code: string) => live(codesById.get(code.toUpperCase()));
export const getProblem = (slug: string) => live(problemsBySlug.get(slug));

export const getPopularCodes = () => POPULAR.flatMap((code) => getCode(code) ?? []);

// URLs use the lowercase code, e.g. /codes/p0420.
export const codePath = (code: string) => `/codes/${code.toLowerCase()}`;
export const problemPath = (slug: string) => `/problems/${slug}`;

export const relatedCodes = (entry: Entry) =>
  entry.related_codes.flatMap((code) => getCode(code) ?? []);
export const relatedProblems = (entry: Entry) =>
  entry.related_problems.flatMap((slug) => getProblem(slug) ?? []);

// Groups entries by car system, largest group first.
export function groupBySystem<T extends Entry>(entries: T[]) {
  const groups = new Map<string, T[]>();
  for (const entry of entries) {
    groups.set(entry.system, [...(groups.get(entry.system) ?? []), entry]);
  }
  return [...groups].sort((a, b) => b[1].length - a[1].length);
}

// Shapes an entry for the app's DiagnosisCard.
export const toDiagnosis = (entry: Entry, summary: string): Diagnosis => ({
  summary,
  vehicle: "General guide for most cars. Your car may differ.",
  severity: entry.severity,
  drive_safety: entry.drive_safety,
  safety_note: entry.safety_note,
  causes: entry.causes,
  diy: entry.diy,
  costs: entry.costs,
  cost_note: entry.cost_note,
});
